### ISSUE TITLE
How to make work with code splitting/async loading?

### ISSUE THREAD

**Issue by Samrose-Ahmed** [DTStack/monaco-sql-languages#79]
It seems the setup happens in an odd way, which makes it hard to work when we need to rely on state to load the completionService (load table, catalog metadata). 

We are not seeing the language be registered correctly (when we navigate within SPA and monaco is already loaded)

Is there a way to register the language/completionService from e.g. a useEffect or programmatically, that doesn't rely on global loading?

**Comment by HaydenOrz** [comment]
The language of monaco-sql-languages is registered in exactly the same way as the monaco built-in languages. And the Monaco built-in language is also loaded globally. We want to be consistent with monaco-editor in this regard.

The loading of the language files depends on how you integrate monaco-sql-languages. If you use [monacoEditorWebpackPlugin](https://github.com/microsoft/monaco-editor/tree/main/webpack-plugin) to integrate monaco-sql-languages, the language files provided by monaco-sql-languages will be loaded at the same time as monaco-editor.  If you use other methods of integration, then the loading of the language files depends on when youimport the language's contribution files.

But in fact, the language registration happens when you use the language for the first time. For detail see [onLanguage Api](https://microsoft.github.io/monaco-editor/docs.html#functions/languages.onLanguage.html).

As for the loading of metadata, I personally think it should be decoupled from the registration of the language.

**Comment by HaydenOrz** [comment]
> It seems the setup happens in an odd way, which makes it hard to work when we need to rely on state to load the completionService (load table, catalog metadata).似乎设置以一种奇怪的方式发生，这使得当我们需要依赖状态来加载completionService（加载表、目录元数据）时很难工作。

Hi, @Samrose-Ahmed .
Pls are you still concerned about this issue.  I seem to have misunderstood your question before.  I recently encountered a similar problem, can you describe the problem you are experiencing in more detail  ? (e.g. exception information).

**Comment by Samrose-Ahmed** [comment]
Yes, its not exactly an exception, its more about functionality. I.e. because the initialization requires loading external metadata (which I agree 'should be decoupled from the registration of the language'), there should be some hook to update or set the language settings, that we can programatically call, e.g. when metadata is done loading, or say when metadata changes (imagine different catalogs, etc).

**Comment by HaydenOrz** [comment]
There may have been some misunderstandings in our previous conversations. Because I might be discussing two issues with you.
 I still don't understand why you need monaco-sql-languages to provide a hook. I don't know what you're referring to by updating language settings. If you just want to update completionService. You can call `setLanguagesFeatrures` anywhere.

Code example:
completionService.ts
```ts
class MetaProvider {
	private _catalogs = [];
	private _databases = [];
	private _tables = [];

	fetchCatalog() {
		// ...
		this._catalogs = [some catalogs..]
	}
	fetchDatabase() {
		// ...
		this._databases = [some databases]
	}
	fetchTables() {
		// ...
		this._tables = [some tables]
	}
	get catalogs() {
		return this.catalogs
	}

	get databases() {
		return this._databases
	}

	get Tables() {
		return this._tables
	}
}

export const metaProvider = new MetaProvider();

export const completionService: CompletionService = async function (
	model,
	_position,
	_completionContext,
	suggestions
) {
	if (!suggestions) {
		return Promise.resolve([]);
	}
	const { keywords, syntax } = suggestions;

	const keywordsCompletionItems: ICompletionItem[] = keywords.map((kw) => ({
		label: kw,
		kind: languages.CompletionItemKind.Keyword,
		detail: 'keyword',
		sortText: '2' + kw,
	}));

	let syntaxCompletionItems: ICompletionItem[] = [];

	for (let i = 0; i < syntax.length; i++) {
		const { syntaxContextType, wordRanges } = syntax[i];
		const words = wordRanges.map((wr) => wr.text);

		if(syntaxContextType === SyntaxContextType.CATALOG) {
			syntaxCompletionItems =[
			    ...syntaxCompletionItems, 
                             ...metaProvider.catalogs.map(cat => ({...}))
                         ] 
		}
	}
	return [...syntaxCompletionItems, ...keywordsCompletionItems];
};

```
app.tsx
```tsx
import React, { useEffect } from 'react';
import { setupLanguageFeatures, LanguageIdEnum } from 'monaco-sql-languages';
import { metaProvider, completionService } from './completionService'

setupLanguageFeatures({
	languageId: LanguageIdEnum.TRINO,
	completionService
});

function App () {
	useEffect(() => {
		// invoke meta fetching anyWhere
		metaProvider.fetchCatalog();
		metaProvider.fetchDatabase();
		metaProvider.fetchTables();
	}, [])

	return(
		<MonacoEditor language={LanguageIdEnum.TRINO}/>
	)
}
```

In the example above, you only need to set completionService  up once,  Updates to the metadata are left to metaProvider.

**Comment by Samrose-Ahmed** [comment]
But that's not how it works in reality in frontend/React code, the completion service won't be a stateless class/function but rather a hook to avoid re fetching again and again.

**Comment by HaydenOrz** [comment]
Closed because of inactivity
