### ISSUE TITLE
【BUG】Dependency path error problem

### ISSUE THREAD

**Issue by resetsix** [DTStack/monaco-sql-languages#89]
First of all, I appreciate your efforts to fix the wrong path issue with `dt-sql-parser`.

I found a problem: installing `monaco-sql-languages` still encounters the `dt-sql-parser` wrong path (node_modules\dt-sql-parser\src\xxx') problem. So I hope `monaco-sql-languages` can also fix this error. As well as being able to update the documentation

Thanks again.

**Comment by HaydenOrz** [comment]
Confirm that the error is being reported by TypeScript.  

If yes, then the issue has been fixed in dt-sql-parser. see https://github.com/DTStack/dt-sql-parser/pull/233.  A new version of dt-sql-parser will be released this week.

If not, then I need more detailed error information.

Please close this issue after confirming that the issue has been fixed, or we will close it in a week.

**Comment by resetsix** [comment]
> Confirm that the error is being reported by TypeScript.
> 
> If yes, then the issue has been fixed in dt-sql-parser. see [DTStack/dt-sql-parser#233](https://github.com/DTStack/dt-sql-parser/pull/233). A new version of dt-sql-parser will be released this week.
> 
> If no, then I need more detailed error information.
> 
> Please close this issue after confirming that the issue has been fixed, or we will close it in a week.

No more questions, thank you very much for your reply
